### ISSUE TITLE
Refactor Predicateable and PositionDistrbutable to magnet pattern

### ISSUE THREAD

**Issue by poojke** [CommBank/grimlock#11]

**Comment by AndreasKostler** [comment]
`PositionDistributable` can be refactored in a straight forward way, but using it is a lot harder. Remember, that the magnet pattern is an overloading crutch. The overloaded methods get replaced with one method with one argument: The magnet. In this particular case `def convert(magnet: PositionDistributable) = ???`

However, `PositionDistributable` is used in context (see for instance `Matrix.change`) where it's result type depends on one of the arguments abstract types -  keeping the same API it's impossible to infer the correct types. 

One way to go about is to simply change the matrix API to return an Aux object: 
```scala
class Aux[T <: Tuner](slice: Slice[P], ...)  {
def apply (p: PositionDistributable[slice.S, TypedPipe]) = ??? // code from original Matrix.change goes here
}

def change[...](...) = new Aux(slice, ...)
```

But to be perfectly honest, I don't see the benefit - the type case pattern used now seems perfectly fine.
Maybe I don't quite understand the goal of the refactoring exercise.

**Comment by poojke** [comment]
@AndreasKostler - thanks for looking into this. The goal was to try and present a consistent interface for each API which is 'overloaded'. It would have been nice if we could present a (visually at least - since technically there's not that much difference) consistent pattern for the API signature and usage of it.

Note though that grimlock uses a modified magnet pattern; it applies it to a single argument as opposed to the full argument list. See for example `Operable` in the `pairwise` functions, `Windowable` in the `slide` functions, `Partitionable` in the `split` functions, `Sampleable` in the `subset` functions, `Aggregatable` in the `summary` functions, `Transformable` in the `transform` functions, or `Squashable` in the `squash` functions.

If however, as you point out, it isn't possible/practical to migrate `PositionDistributable` or `Predicteable` to a similar pattern then the best course of action would be to leave them as is. Another possible way around the problem of inferring the type would be to add add types as done here:
https://github.com/CommBank/grimlock/blob/partition/src/main/scala/au/com/cba/omnia/grimlock/framework/Matrix.scala#L337 (in particular the usage of `S`). However, this is far from ideal too.

Lets briefly discuss later today and decide on the best course of action.

**Comment by AndreasKostler** [comment]
Ah ok, I get you. The problem is the dependency on `slice.S` - I can work around this via the `Aux` pattern above or by having two parameter lists for `change` and co. , i.e. `change(...)(p: PositionDistributable)`
Both brake the API so I am not sure if it wins anything at all. 
Thinking about it, I'm not even sure the latter would work.

**Comment by AndreasKostler** [comment]
Oh, I'll have a look at the link you've provided - it looks like it could work. However, there's still the `exactly one argument` issue. I'll do some trying and testing.

**Comment by poojke** [comment]
Refactor to use shapeless.Nat included overall code simplification - magnet pattern is no longer used
