### ISSUE TITLE
Refactor of Value, Schema, Codex and Content

### ISSUE THREAD

**Issue by poojke** [CommBank/grimlock#15]
Both `Value` and `Schema` have a `Codex`. Ideally only a `Value` should have it. Should `Codex.fromValue` return an `Option[T]` instead?

**Comment by AndreasKostler** [comment]
I will look into this.

**Comment by AndreasKostler** [comment]
On second thought - Shouldn't `Value` contain both a `Schema` and a `Codex` as those are what ultimately make up a `Value`?

**Comment by poojke** [comment]
A `Value` is used in two contexts, one as the value in a `Contents`. Here is makes perfect sense to include the `Schema` in the `Value`. There the `Schema` assigns a semantic meaning to the `Value` (this pairing is essentially what the `Contents` is).
The other place where `Value` is used is as a coordinate in `Position`. In this latter context, it doesn't make much sense to require a `Schema` as the coordinate doesn't have a meaning as a feature.

**Comment by AndreasKostler** [comment]
Then `isValid` would make more sense as a member of `Content` as it requires a `Schema` and a `Value`.

**Comment by AndreasKostler** [comment]
Also, `Content.toShortString` disregards the `Schema` and simply returns `Value.toShortString` - is that intended?

**Comment by AndreasKostler** [comment]
So my suggestion(s) would be:
1) Remove codex from `Schema` and parameterise `Schema` on the type of the underlying value (i.e. `Double` for `DoubleValue` etc.)
2) From my understanding `isValid` is only valid in the context of `Content` making the equality check unnecessary
Removing codex from `Schema` will have wider implications, i.e. for parsing. 
I am happy to do this but it's no small feat. I would estimate a couple of days minimum.

**Comment by poojke** [comment]
Nice idea to put `isValid` on `Content`; it does make more sense to check/filter in the context of a `Content`. I assume the new `isValid` would then use the range/legal values from the `Schema` to validate the `Content`? The `Schema` then becomes just static data; it captures the type of the data and it's legal values only. Decoding is done by the `Codex` and validation is done by the `Content`. Is that what you have in mind too?

**Comment by poojke** [comment]
With regards to `Content.toShortString`; please have a look here: https://github.com/CommBank/grimlock/blob/master/src/main/scala/au/com/cba/omnia/grimlock/framework/Cell.scala#L56. It may not be a good reason, but this is why the `Schema` is ignored. Perhaps it would benefit from a better name?

**Comment by poojke** [comment]
With regards to the suggestions; could you elaborate a little what the parameterised `Schema` would look like and why it needs the underlying value as a type parameter? As you say, it's a fair bit of work. Let's discuss during standup how best to plan this and what resources you'd need.
