### ISSUE TITLE
Multi-dimensional Slice

### ISSUE THREAD

**Issue by poojke** [CommBank/grimlock#18]
Should it be possible to aggregate over arbitrary dimensions (for example 2 out of 4)? Following on, is cubeing functionality necessary?

**Comment by hgrano** [comment]
@poojke is this closed by the `Along`/`Over` multiple dimensions?

**Comment by poojke** [comment]
Thanks @hgrano, yes this can be closed. Good find!

**Comment by hgrano** [comment]
Closed by https://github.com/CommBank/grimlock/pull/88
